openapi: 3.0.1
info:
  title: workshop-rh
  x-cortex-tag: workshop-rh
  x-cortex-type: service
  x-cortex-owners:
  - type: EMAIL
    email: randy.herasme@cortex.io
  x-cortex-git:
    github:
      repository: Cortex-Customer-Engineering/workshop-rh
      alias: default
