openapi: 3.0.1
info:
  title: workshop-rh
  description: RH Example!
  x-cortex-tag: 
  x-cortex-type: service
  x-cortex-owners: workshop-rh1
  - type: EMAIL
    email: randy.herasme@cortex.io
  x-cortex-git:
    github:
      repository: Cortex-Customer-Engineering/workshop-rh
      alias: default
